# Generated by Django 3.0.2 on 2020-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='number_plate',
            field=models.CharField(default=1324354, max_length=10),
            preserve_default=False,
        ),
    ]
