# Generated by Django 3.0.2 on 2020-02-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userdata_number_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='altemail',
        ),
    ]
