# Generated by Django 3.0.2 on 2020-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userdata_altemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='finedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('numberplate', models.CharField(max_length=40)),
                ('fine', models.CharField(max_length=40)),
            ],
        ),
    ]
