# Generated by Django 3.0.2 on 2020-03-24 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_finedata_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finedata',
            name='datefield',
        ),
        migrations.AddField(
            model_name='finedata',
            name='d',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
